# Generated by Django 5.2.4 on 2026-04-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('lichess_username', models.CharField(blank=True, max_length=100)),
            ],
            options={'ordering': ['display_name']},
        ),
    ]
