# Generated by Django 5.2.4 on 2026-05-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_contactmessage_team_member_avatar_member_draws_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwissTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('done', 'Finished')], default='draft', max_length=20)),
                ('rounds_played', models.PositiveSmallIntegerField(default=0)),
                ('rounds_target', models.PositiveSmallIntegerField(default=5, help_text='Maximum Swiss rounds (organisers usually set near ceil(log2(n))).')),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('counts_for_club_elo', models.BooleanField(default=True, help_text='When results are recorded, create/update OTB Match rows so club ELO updates.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SwissRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='club.swisstournament')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('tournament', 'number')},
            },
        ),
        migrations.CreateModel(
            name='SwissPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.PositiveSmallIntegerField(default=1)),
                ('result', models.CharField(blank=True, choices=[('', 'Pending'), ('1-0', 'White wins'), ('0-1', 'Black wins'), ('1/2-1/2', 'Draw')], max_length=10)),
                ('black', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swiss_pairings_black', to='club.member')),
                ('club_match', models.OneToOneField(blank=True, help_text='Linked OTB club match when this pairing counts for official ELO.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swiss_pairing', to='club.match')),
                ('white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swiss_pairings_white', to='club.member')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='club.swissround')),
            ],
            options={
                'ordering': ['board'],
                'unique_together': {('round', 'board')},
            },
        ),
        migrations.CreateModel(
            name='SwissParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swiss_entries', to='club.member')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='club.swisstournament')),
            ],
            options={
                'unique_together': {('tournament', 'member')},
            },
        ),
    ]
