# Generated by Django 5.2.4 on 2026-04-03 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lichess_game_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('pgn', models.TextField(help_text='Portable Game Notation of the full game')),
                ('time_control', models.CharField(blank=True, max_length=50)),
                ('result', models.CharField(help_text='e.g. 1-0, 0-1, 1/2-1/2', max_length=10)),
                ('played_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('player_black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lichess_games_as_black', to='club.member')),
                ('player_white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lichess_games_as_white', to='club.member')),
            ],
            options={'ordering': ['-played_at']},
        ),
        migrations.CreateModel(
            name='GameAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('depth', models.IntegerField(default=20, help_text='Stockfish search depth used')),
                ('white_avg_centipawn_loss', models.FloatField(blank=True, null=True)),
                ('black_avg_centipawn_loss', models.FloatField(blank=True, null=True)),
                ('white_blunders', models.IntegerField(default=0)),
                ('black_blunders', models.IntegerField(default=0)),
                ('white_mistakes', models.IntegerField(default=0)),
                ('black_mistakes', models.IntegerField(default=0)),
                ('white_inaccuracies', models.IntegerField(default=0)),
                ('black_inaccuracies', models.IntegerField(default=0)),
                ('analysed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='ai_pipeline.game')),
            ],
            options={'verbose_name_plural': 'Game Analyses'},
        ),
        migrations.CreateModel(
            name='MoveEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('is_white', models.BooleanField(help_text='True if this is a white move')),
                ('move_san', models.CharField(help_text='Standard Algebraic Notation, e.g. Nf3', max_length=10)),
                ('best_move_san', models.CharField(blank=True, max_length=10)),
                ('eval_before', models.FloatField(help_text='Centipawn evaluation before the move')),
                ('eval_after', models.FloatField(help_text='Centipawn evaluation after the move')),
                ('centipawn_loss', models.FloatField(default=0)),
                ('classification', models.CharField(choices=[('best', 'Best'), ('excellent', 'Excellent'), ('good', 'Good'), ('inaccuracy', 'Inaccuracy'), ('mistake', 'Mistake'), ('blunder', 'Blunder')], default='good', max_length=20)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_evaluations', to='ai_pipeline.gameanalysis')),
            ],
            options={'ordering': ['analysis', 'move_number', '-is_white']},
        ),
        migrations.CreateModel(
            name='PlayerInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('opening', 'Opening'), ('middlegame', 'Middlegame'), ('endgame', 'Endgame'), ('tactics', 'Tactics'), ('time_management', 'Time Management'), ('positional', 'Positional Play')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed insight with examples')),
                ('recommendation', models.TextField(help_text='Suggested improvement actions')),
                ('games_analysed', models.IntegerField(default=0)),
                ('avg_centipawn_loss', models.FloatField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='club.member')),
            ],
            options={'ordering': ['-generated_at']},
        ),
    ]
